language: node_js
sudo: true
dist: trusty
node_js:
  - "4"
  - "6"
install:
  - npm i -g npm
  - node --version
  - npm --version
  - npm install
script: npm test
notifications:
  email:
    on_failure: change
after_success:
  - npm run coveralls
